export const SET_STRUCTURE_CONSTANTS = {
  TITLE: "Set Structure",
  SUBTITLE: "Configure the number of sets and customize individual set lengths throughout the event.",
  STRUCTURE_TYPE_LABEL: "Structure Type",
  TIME_BASED_LABEL: "Time Based (Minutes)",
  SONG_COUNT_LABEL: "Song Count",
  NUMBER_OF_SETS_LABEL: "Number of Sets",
  DEFAULT_LENGTH_LABEL: "Default Length",
  APPLY_TO_ALL_BUTTON: "Apply to All Sets",
  ADD_SET_BUTTON: "Add Set",
  REMOVE_SET_BUTTON: "Remove",
  SET_NAME_PLACEHOLDER: "Set Name (e.g. Dinner Set)",
  MINUTES_UNIT: "minutes",
  SONGS_UNIT: "songs",
  APPROX_LABEL: "Approx.",
  TOTAL_PLANNED_LABEL: "Total Planned",
  SET_SINGULAR: "Set",
  SET_PLURAL: "Sets",
  MINUTES_SHORT: "min",
  HOURS_SHORT: "hr",
} as const;
